package xigua.battle.of.elements.model;

public enum EventType {
    BATTLE_STARTED, BATTLE_ACTION_STARTED, BATTLE_ACTION_ENDED, BATTLE_ELEMENT_SUMMONED, BATTLE_MAGIC_CASTED,
    BATTLE_MAGIC_NOT_CASTED, BATTLE_MAGIC_TARGET_CHOSEN, BATTLE_AFTER_MAGIC, BATTLE_PHYSICAL_TARGET_CHOSEN,
    BATTLE_AFTER_PHYSICAL_ATTACK;
}
