package xigua.battle.of.elements.model;

public enum EventType {
    BATTLE_STARTED, BATTLE_ACTION_STARTED, BATTLE_ACTION_ENDED, BATTLE_ELEMENT_SUMMONED, BATTLE_MAGIC_CASTED, BATTLE_TARGET_FOR_ATTACK_CHOSEN, BATTLE_AFTER_ATTACK;
}
