package xigua.battle.of.elements.model;

public enum EventType {
    BATTLE_STARTED, BATTLE_ACTION_STARTED, BATTLE_ACTION_ENDED, BATTLE_ELEMENT_SUMMONED, BATTLE_MAGIC_CASTED, BATTLE_ATTACK_TARGET_CHOSEN, BATTLE_AFTER_ATTACK, BATTLE_DEFEND_TARGET_CHOSEN, BATTLE_AFTER_DEFEND, BATTLE_HEAL_TARGET_CHOSEN, BATTLE_AFTER_HEAL;
}
